### ISSUE TITLE
SISSOJob requires the SISSO executable to be in the path.

### ISSUE THREAD

**Issue by zw1900686** [Matgenix/pysisso#20]
Sir，I'd like to ask you a question about installation. When I ran the first example, I encountered the following error.

SISSOJob requires the SISSO executable to be in the path.
Default executable name is "SISSO" and you provided "SISSO".
Download the SISSO code at https://github.com/rouyang2017/SISSO and compile the executable or fix the name of your executable.

Is there a problem with my installation?

**Comment by davidwaroquiers** [comment]
Hello,

pysisso is just a wrapper around SISSO. You still need to compile the SISSO code (as stated in the message) and have the SISSO executable in your PATH. To check if this is indeed the case, just type "which SISSO" in your terminal.

Best,

David
