### ISSUE TITLE
OMP Usage

### ISSUE THREAD

**Issue by AYANG005** [Matgenix/pysisso#21]
Hi Dr. Waroquiers, 

I have a query regarding the OMP. It was stated that OMP was to be applied before applying SISSO in the documentation. However, it was also stated that OMP would be a special case of SISSO. 

Could I check if this means OMP is already included in the .fit of the SISSORegressor class, and that we do not have to implement it first, followed by the regression? That is, having 

sisso_regressor = SISSORegressor(...)
sisso_regressor.fit(...) 

would be enough to run the SISSO algorithm?

Thanks.
P.s Regarding the sisso executable path email I sent last week, it executes fine now thanks.

**Comment by davidwaroquiers** [comment]
Hello,

No the SISSORegressor does not apply OMP to filter out features. What you can do is to use the OMP classmethod of SISSORegressor to instantiate an "OMP run of SISSO":

omp = SISSORegressor.OMP(...)
omp.fit(...)

You could also put that in a sklearn Pipeline with 1/ the OMP and 2/ the "normal" SISSO.


Best,


David

**Comment by AYANG005** [comment]
Hi Dr. Waroquiers,

Ok thanks! Would it be possible for me to ask about one more thing regarding pysisso?

For the attribute "rung" in SISSORegressor, its described as "rung of the feature space to be constructed". However I don't quite get what this is referring to. Would it be describing the "depth" of the tree when composing the operations?

Sorry for the trouble.
Thanks.

**Comment by davidwaroquiers** [comment]
Hello,


Exactly, the rung is indeed the number of iterative applications of the mathematical operations in the construction of the complex features.


Best,


David
