### ISSUE TITLE
SISSOJob requires the SISSO executable to be in the path

### ISSUE THREAD

**Issue by MarcDuquesnoy** [Matgenix/pysisso#22]
Dear David, 

thank you for providing use a Python version of the SISSO approach. I am trying to run your example for the regression and I got this error : ""SISSOJob requires the SISSO executable to be in the path. Default executable name is "SISSO" and you provided "SISSO". Download the SISSO code at https://github.com/rouyang2017/SISSO and compile the executable or fix the name of your executable. ""

I already got the executable namely "sisso.x" from the repository you mentioned. However, I misunderstand the next steps to complete the installation..  Should I use also other files from such repository ?

Can you orientate me ?

Best,

**Comment by davidwaroquiers** [comment]
Dear Marc,

The default name for the SISSO executable is "SISSO". In the sklearn-like interface, I did not add the possibility to change the executable unfortunately. This should not be too difficult to do though. I'll put that in the list of things to do. In the meantime, you could for example copy your "sisso.x" executable to "SISSO".

Best,

David

**Comment by davidwaroquiers** [comment]
I hope the previous advice solved your problem.

**Comment by MarcDuquesnoy** [comment]
Dear David, 

thank you for your response ! I will try to figure out with your suggestions since it is true the excecutable is SISSO instead of sisso.x (I renamed it a long time ago and I did'nt remember why). So for now it is much better for me to add it in the PATH.

Best, 
Marc

PS : sorry for my delayed response I didn't see the notification last week...
