### ISSUE TITLE
Operation set error

### ISSUE THREAD

**Issue by AYANG005** [Matgenix/pysisso#23]
Dear David,

When applying all operations in the operation set "(+)(-)(*)(/)(exp)(exp-)(^-1)(^2)(^3)(sqrt)(cbrt)(log)(|-|)(scd)(^6)", I end up having the following error listed below.

**Output:**
Job return code is -9. Terminating...
Traceback (most recent call last):
  File "/home/PycharmProjects/Pysisso_test/Diabetes Regression Test.py", line 34, in <module>
    sisso_regressor.fit(diabetes_X_train, diabetes_y_train) #generated predicted graph
  File "/home/anaconda3/envs/mse-ml/lib/python3.8/site-packages/pysisso/sklearn.py", line 271, in fit
    c.run()
  File "/home/anaconda3/envs/mse-ml/lib/python3.8/site-packages/custodian/custodian.py", line 372, in run
    self._run_job(job_n, job)
  File "/home/anaconda3/envs/mse-ml/lib/python3.8/site-packages/custodian/custodian.py", line 510, in _run_job
    raise ReturnCodeError(s, True)
custodian.custodian.ReturnCodeError: Job return code is -9. Terminating...

Could I check if there would be a way to fix this other than limiting operations to "(+)(*)(^2)(^3)(^-1)(cos)(sin)"? Also what would be the cause of this error?

Below is my code for reference.
Thanks.

**Code:**
import matplotlib.pyplot as plt
import numpy as np
from pysisso.sklearn import SISSORegressor
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from pysisso.outputs import SISSOOut
from joblib import dump, load

# Define general parameters
NPOINTS = 100  # Number of data points
SIGMA = 0.5  # Randomness in the data points
PLOT_FIGURES = False  # whether to interactively plot the figures with matplotlib
SAVE_FIGURES = False  # whether to save the matplotlib figures to a file
CLEAN_RUN_DIR = False  # whether to remove the SISSO_dir after the fit

diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)

diabetes_X_train = diabetes_X[:-20]
diabetes_X_test = diabetes_X[-20:]

diabetes_y_train = diabetes_y[:-20]
diabetes_y_test = diabetes_y[-20:]

sisso_regressor = SISSORegressor(
    rung=3,#rung of the feature space to be constructed i.e number of iterative applications of the mathematical operations in the construction of the complex features. i.e depth
    opset="(+)(-)(*)(/)(exp)(exp-)(^-1)(^2)(^3)(sqrt)(cbrt)(log)(|-|)(scd)(^6)", #"(+)(-)(*)(exp)(exp-)(^-1)(^2)(^3)(sqrt)(^6)(sin)(cos)"
    desc_dim=3,#number of descriptors used, i.e number of columns composed
    clean_run_dir=CLEAN_RUN_DIR,
    maxcomplexity=3     #max feature complexity (number of operators in a feature) i.e overall no. aft combining cols.
)

sisso_regressor.fit(diabetes_X_train, diabetes_y_train) #generated predicted graph
"""
filename = 'model.sav'
dump(sisso_regressor, filename)
"""
diabetes_y_pred = sisso_regressor.predict(diabetes_X_test)

sisso_out = SISSOOut.from_file(filepath="SISSO_dir/SISSO.out")
sisso_model = sisso_out.model

descriptors = [str(d) for d in sisso_model.descriptors]
#print(sisso_model.descriptors)
#print(descriptors)
coeff = [d for d in sisso_model.coefficients[0]] #note, .coeff is 2D so must have [0] first
#print(coeff)

for i in coeff:
    t = coeff.index(i)
    i = round(i)
    if i>=0: i = "+" + str(i)
    elif i<0: i = str(i)
    coeff[t]=i

output = "Model:"
for i in range(len(descriptors)):
    output += " " + coeff[i] + descriptors[i] + " "
print(output)
print("RMSE: " + str(sisso_model.rmse[0])) #Note, .rmse is 2D so must have [0]
print("Dimension: " + str(sisso_model.dimension))

**Comment by davidwaroquiers** [comment]
Dear Ayang,

Could you provide the output files from the SISSO_dir ? I would guess that it is a SISSO issue but without additional information, I cannot tell for sure.

David

**Comment by AYANG005** [comment]
Dear David,

Attached are the files.

Thanks.



[SISSO_in.txt](https://github.com/Matgenix/pysisso/files/6650484/SISSO_in.txt)
[SISSO_log.txt](https://github.com/Matgenix/pysisso/files/6650485/SISSO_log.txt)
[SISSO_out.txt](https://github.com/Matgenix/pysisso/files/6650486/SISSO_out.txt)
[custodian.txt](https://github.com/Matgenix/pysisso/files/6650483/custodian.txt)

**Comment by FuzhuLiu** [comment]
I also have the same problem:
custodian.custodian.ReturnCodeError: Job return code is -11. Terminating...

**Comment by davidwaroquiers** [comment]
Dear Ayang,

It seems that the issue is an operating system problem. Likely, your job was killed because it used too much memory. And indeed, with a rung 3, 10 scalar features and this number of operators, the feature construction might lead to an extremely large number of complex features. Could you try first rung 1 (and then rung 2 if rung 1 is working) ?

Best,

David

**Comment by AYANG005** [comment]
Hi David,

For the instances of rung = 1, 2, it works. Thanks.

**Comment by drakeyu** [comment]
Hi David,
I have posted files in this google drive:
https://drive.google.com/drive/folders/1n_R1aLO1gpKU5KTa8pCLOPctDU-JnEMV?usp=sharing 
Thanks for the help!
